version: '3.9'

services:
  sfnapi:
    container_name: sfn-api
    image: sfnapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
    env_file:
      - .env
